name: Timed Clock In
on:
  push

jobs:
  Clock-In:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary tools
        run: sudo apt install python3.9 python3-requests
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Clock in
        run: python3 ${{ github.workspace }}/main.py
